//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy_City.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailabilityPhar
    {
        public int IDPharmacy { get; set; }
        public int IDMedication { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
    
        public virtual Medication Medication { get; set; }
        public virtual Pharmacy Pharmacy { get; set; }
    }
}
